{{- if not .Values.worker.config.bootloader.fsEndpoints }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   {{- include "worker.labels" . | nindent 4 }}
  name: {{ .Values.worker.name }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "worker.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "codesealer.serviceAccountName" . | quote }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.worker.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.worker.image }}:{{ .Values.worker.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.worker.config.network.listen }}
              protocol: TCP
          volumeMounts:
            - name: config-toml
              mountPath: /etc/codesealer-core/config.toml
              subPath: config.toml
            - name: {{ .Values.worker.secret.name }}
              mountPath: /etc/codesealer-core/certs
              readOnly: true
            - name: modsec-conf
              mountPath: /etc/codesealer-core/modsec.conf
              subPath: modsec.conf
            - name: modsecurity-conf
              mountPath: /etc/codesealer-core/modsecurity/modsecurity.conf
              subPath: modsecurity.conf
            - name: crs-setup-conf
              mountPath: /etc/codesealer-core/modsecurity/crs-setup.conf
              subPath: crs-setup.conf
      volumes:
        - name: config-toml
          configMap:
            name: config-toml
        - name: {{ .Values.worker.secret.name }}
          secret:
            secretName: {{ .Values.worker.secret.name }}
        - name: modsec-conf
          configMap:
            name: modsec-conf
        - name: modsecurity-conf
          configMap:
            name: modsecurity-conf
        - name: crs-setup-conf
          configMap:
            name: crs-setup-conf
{{- end }}