{{ $tls := fromYaml ( include "worker.gen-certs" . ) }}
{{- if .Values.worker.cert.create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}  
  name: {{ .Values.worker.cert.name }}
  {{- if .Values.sidecar.enabled }}
  namespace: {{ .Values.sidecar.ingress.namespace }}
  {{ else }}
  namespace: {{ .Values.namespace }}
  {{- end }}
type: {{ .Values.worker.cert.type }}
data:
  # Cert for {{ include "worker.service.fullname" . }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
  ca.crt: {{ $tls.caCert }}
{{- end }}
---
