{{ $tls := fromYaml ( include "redis.gen-certs" . ) }}
{{- if .Values.redis.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}  
  name: {{ .Values.redis.secret.name }}
  namespace: {{ .Values.redis.namespace }}
type: {{ .Values.redis.secret.type }}
data:
  # Cert for {{ include "redis.service.fullname" . }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
  ca.crt: {{ $tls.caCert }}
{{- end }}
---