apiVersion: v1
kind: ConfigMap
metadata:
  name: modsec-conf
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  {{- if .Values.sidecar.enabled }}
  namespace: {{ .Values.sidecar.ingress.namespace }}
  {{ else }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  modsec.conf: |
    Include coreruleset/modsecurity.conf

    # OWASP CRS v4.0.0 rules
    Include coreruleset/crs-setup.conf

    {{- if .Values.worker.waf.rules.rules901 }}
    Include coreruleset/rules/REQUEST-901-INITIALIZATION.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules905 }}
    Include coreruleset/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules911 }}
    Include coreruleset/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules913 }}
    Include coreruleset/rules/REQUEST-913-SCANNER-DETECTION.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules920 }}
    Include coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules921 }}
    Include coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules922 }}
    Include coreruleset/rules/REQUEST-922-MULTIPART-ATTACK.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules930 }}
    Include coreruleset/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules931 }}
    Include coreruleset/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules932 }}
    Include coreruleset/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules933 }}
    Include coreruleset/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules934 }}
    Include coreruleset/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules941 }}
    Include coreruleset/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules942 }}
    Include coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules943 }}
    Include coreruleset/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules944 }}
    Include coreruleset/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules949 }}
    Include coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules950 }}
    Include coreruleset/rules/RESPONSE-950-DATA-LEAKAGES.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules951 }}
    Include coreruleset/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules952 }}
    Include coreruleset/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules953 }}
    Include coreruleset/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules954 }}
    Include coreruleset/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules955 }}
    Include coreruleset/rules/RESPONSE-955-WEB-SHELLS.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules959 }}
    Include coreruleset/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
    {{- end }}
    {{- if .Values.worker.waf.rules.rules980 }}
    Include coreruleset/rules/RESPONSE-980-CORRELATION.conf
    {{- end }}
