{{ if .Values.manager.init }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: organizations-init
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  organizations-init.json: {{ .Values.manager.init | toJson }}
{{ end }}
