apiVersion: v1
kind: ConfigMap
metadata:
  name: modsec-conf
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  namespace: {{ .Values.worker.ingress.namespace }}
data:
  modsec.conf: |
    Include modsecurity/modsecurity.conf

    # OWASP CRS v3 rules
    Include modsecurity/crs-setup.conf
    # Include modsecurity/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    Include modsecurity/rules/REQUEST-901-INITIALIZATION.conf
    Include modsecurity/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
    Include modsecurity/rules/REQUEST-910-IP-REPUTATION.conf
    Include modsecurity/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
    Include modsecurity/rules/REQUEST-912-DOS-PROTECTION.conf
    Include modsecurity/rules/REQUEST-913-SCANNER-DETECTION.conf
    Include modsecurity/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    Include modsecurity/rules/REQUEST-921-PROTOCOL-ATTACK.conf
    Include modsecurity/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
    Include modsecurity/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
    Include modsecurity/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
    Include modsecurity/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
    Include modsecurity/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
    Include modsecurity/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    Include modsecurity/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
    Include modsecurity/rules/REQUEST-949-BLOCKING-EVALUATION.conf
    Include modsecurity/rules/RESPONSE-950-DATA-LEAKAGES.conf
    Include modsecurity/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
    Include modsecurity/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    Include modsecurity/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
    Include modsecurity/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
    Include modsecurity/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
    Include modsecurity/rules/RESPONSE-980-CORRELATION.conf
    # Include modsecurity/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
