apiVersion: v1
kind: ConfigMap
metadata:
  name: config-manager-toml
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  config.toml: |     
    [manager]
    listen = "0.0.0.0:{{ .Values.manager.config.listen }}"
    tls = {{ .Values.manager.config.tls }}
    certFile = {{ .Values.manager.config.certFile | quote }}
    keyFile = {{ .Values.manager.config.keyFile | quote }}
    letsEncrypt = {{ .Values.manager.config.letsEncrypt }}
    letsEncryptDomain = {{ .Values.manager.config.letsEncryptDomain | quote }}

    [[manager.backend]]
    backendID = {{ .Values.manager.config.backend.backendID | quote }}
    redisAddress = ["{{ include "redis.serviceName" . }}"]
    redisUser = "default"
    redisPassword = "${REDIS_PASSWORD}"
    redisUseTLS = {{ .Values.worker.config.bootloader.redisUseTLS }}
    redisIgnoreTLS = {{ .Values.worker.config.bootloader.redisIgnoreTLS }}
    redisConnectTimeout = {{ .Values.worker.config.bootloader.redisConnectTimeout }}
    redisReadTimeout = {{ .Values.worker.config.bootloader.redisReadTimeout }}
    redisWriteTimeout = {{ .Values.worker.config.bootloader.redisWriteTimeout }}
    influxAddress = {{ .Values.influxDB.influxAddress | quote }}
    influxToken = {{ .Values.influxDB.influxToken | quote }}
    influxIgnoreTLS = {{ .Values.influxDB.influxIgnoreTLS }}
