apiVersion: v1
kind: ConfigMap
metadata:
  name: config-toml-manager
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  namespace: {{ .Values.ingress.namespace }}
data:
  config.toml: |
    [manager]
    listen = "0.0.0.0:{{ .Values.manager.config.listen }}"
    tls = {{ .Values.manager.config.tls }}
    certFile = "{{ .Values.manager.config.certFile }}"
    keyFile = "{{ .Values.manager.config.keyFile }}"
    letsEncrypt = {{ .Values.manager.config.letsEncrypt }}
    letsEncryptDomain = "{{ .Values.manager.config.letsEncryptDomain }}"

    [[manager.backend]]
    backendID = "{{ .Values.manager.config.backend.backendID }}"
    redisAddress = "redis://{{ .Values.redis.name }}"
    redisIgnoreTLS = {{ .Values.redis.config.redisIgnoreTLS }}
    redisConnectTimeout = {{ .Values.redis.config.redisConnectTimeout }}
    redisReadTimeout = {{ .Values.redis.config.redisReadTimeout }}
    redisWriteTimeout = {{ .Values.redis.config.redisWriteTimeout }}
    influxAddress = "{{ .Values.influxDB.influxAddress }}"
    influxToken = "{{ .Values.influxDB.influxToken }}"
    influxIgnoreTLS = {{ .Values.influxDB.influxIgnoreTLS }}
