apiVersion: v1
kind: ConfigMap
metadata:
  name: config-toml
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  {{- if .Values.sidecar.enabled }}
  namespace: {{ .Values.sidecar.ingress.namespace }}
  {{ else }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  config.toml: |
    [network]
    listen = "0.0.0.0:{{ .Values.worker.config.network.listen }}"
    tls = {{ .Values.worker.config.network.tls }}
    tlsMinVersion = {{ .Values.worker.config.network.tlsMinVersion | quote }}
    certFile = {{ .Values.worker.config.network.certFile | quote }}
    keyFile = {{ .Values.worker.config.network.keyFile | quote }}
    letsEncrypt = {{ .Values.worker.config.network.letsEncrypt }}
    ignoreTLS = {{ .Values.worker.config.network.ignoreTLS }}
    disallowLocal = {{ .Values.worker.config.network.disallowLocal }}
    disallowPrivate = {{ .Values.worker.config.network.disallowPrivate }}
    remoteTimeout = {{ .Values.worker.config.network.remoteTimeout }}
    behindProxy = {{ .Values.worker.config.network.behindProxy }}
    useProxyProtocol = {{ .Values.worker.config.network.useProxyProtocol }}

    [bootloader]
    redisAddress = ["{{ include "redis.serviceName" . }}"]
    redisUser = "default"
    redisPassword = "${REDIS_PASSWORD}"
    redisUseTLS = {{ .Values.worker.config.bootloader.redisUseTLS }}
    redisMaxConn = {{ .Values.worker.config.bootloader.redisMaxConn }}
    redisIgnoreTLS = {{ .Values.worker.config.bootloader.redisIgnoreTLS }}
    redisConnectTimeout = {{ .Values.worker.config.bootloader.redisConnectTimeout }}
    redisReadTimeout = {{ .Values.worker.config.bootloader.redisReadTimeout }}
    redisWriteTimeout = {{ .Values.worker.config.bootloader.redisWriteTimeout }}
    wafConf = {{ .Values.worker.config.bootloader.wafConf | quote }}
    wafAuditLog = {{ .Values.worker.config.bootloader.wafAuditLog }}
    fsEndpoints = false
    sessionBackend = {{ .Values.worker.config.bootloader.sessionBackend | quote }}

    [cache]
    folder = {{ .Values.worker.config.cache.folder | quote }}
    maxFileSize = {{ .Values.worker.config.cache.maxFileSize }}
    maxSize = {{ .Values.worker.config.cache.maxSize }}
