{{ $tls := fromYaml ( include "manager.gen-certs" . ) }}
{{- if .Values.manager.cert.create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}  
  name: {{ .Values.manager.cert.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  # Cert for {{ include "manager.service.fullname" . }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
  ca.crt: {{ $tls.caCert }}
{{- end }}
---
