apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   {{- include "manager.labels" . | nindent 4 }}
  name: {{ include "manager.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "manager.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "manager.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "codesealer.serviceAccountName" . | quote }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "manager.name" . }}
          image: "{{ .Values.image.repository }}/{{ .Values.manager.image }}:{{ .Values.manager.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: {{ .Values.manager.service.name }}
            hostPort: {{ .Values.manager.service.port }}
            containerPort: {{ .Values.manager.config.listen }}
            protocol: TCP
          env:
          - name: REDIS_PASSWORD
            {{ if .Values.redis.install }}
            valueFrom:
              secretKeyRef:
                name: {{ include "redis.secretName" .Subcharts.redis }}
                key: {{ include "redis.secretPasswordKey" .Subcharts.redis }}
            {{ else }}
            value: {{ .Values.redis.auth.password }}
            {{ end }}
          volumeMounts:
            - mountPath: /etc/codesealer-core/config.toml
              subPath: config.toml
              name: config-toml
            {{ if .Values.manager.init }}
            - mountPath: /etc/codesealer-core/organizations-init.json
              subPath: organizations-init.json
              name: organizations-init-volume
            {{ end }}
            - name: core-manager-data
              mountPath: /var/lib/core-manager
              readOnly: false
            - mountPath: /etc/core-manager
              name: {{ .Values.manager.cert.name }}
              readOnly: true
      restartPolicy: {{ .Values.manager.restartPolicy }}
      volumes:
        - name: config-toml
          configMap:
            name: config-manager-toml
        {{ if .Values.manager.init }}
        - name: organizations-init-volume
          configMap:
            name: organizations-init
        {{ end }}
        - name: core-manager-data
          persistentVolumeClaim:
            claimName: core-manager-pv-claim
        - name: {{ .Values.manager.cert.name }}
          secret:
            secretName: {{ .Values.manager.cert.name }}
