apiVersion: v1
kind: Service
metadata:
  labels:
   {{- include "manager.labels" . | nindent 4 }}
  name: {{ include "manager.serviceName" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: https-{{ .Values.manager.config.listen }}
      port: {{ .Values.manager.service.port }}
      targetPort: {{ .Values.manager.config.listen }}
  selector:
    {{- include "manager.selectorLabels" . | nindent 6 }}
