apiVersion: v1
kind: Secret
metadata:
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}  
  {{- range $name := .Values.imagePullSecrets }} 
  name: {{ $name.name }}
  {{- end }}
  namespace: {{ .Values.ingress.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "codesealer.imagePullSecret" . }}
---