{{- if .Values.sidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
   {{- include "codesealer.labels" . | nindent 4 }}
  name: {{ template "codesealer.imagePullSecretName" . }}
  namespace: {{ .Values.sidecar.ingress.namespace }}
type: kubernetes.io/dockerconfigjson
data:
 .dockerconfigjson: {{ template "codesealer.imagePullSecret" . }}
{{- end }}
