{{- if and (not .Values.sidecar.enabled) (index .Values "ingress-nginx" "install") -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "worker.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "codesealer.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: nginx
spec:
  {{- if (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: nginx
  {{- end }}
  defaultBackend:
    service:
      name: {{ include "worker.name" . }}
      port:
        number: {{ .Values.worker.service.port }}
{{- end }}
