{{- if not .Values.manager.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webhook.name }}
  labels:
   {{- include "webhook.labels" . | nindent 4 }}
  namespace: {{ .Values.webhook.namespace }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "webhook.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "codesealer.serviceAccountName" . | quote }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.webhook.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.webhook.image }}:{{ .Values.webhook.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webhook.service.targetPort }}
              name: webhook
              protocol: TCP
          env:
          {{- range $key, $value := .Values.webhook.env }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: {{ .Values.probes.failureThreshold }}
            httpGet:
              path: /liveness
              port: {{ .Values.webhook.service.targetPort }}
              scheme: {{ .Values.webhook.service.scheme }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.webhook.service.targetPort }}
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          volumeMounts:
            - name: {{ include "webhook.secretName" . }}
              mountPath: /certs
              readOnly: true
            - name: codesealer-mutating-webhook-patch
              mountPath: /patch
      volumes:
        - name: {{ include "webhook.secretName" . }}
          secret:
            secretName: {{ include "webhook.secretName" . }}
        - name: codesealer-mutating-webhook-patch
          configMap:
            name: codesealer-mutating-webhook-patch
{{- end }}