{{- if .Values.worker.config.bootloader.fsEndpoints }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.serviceName" . }}
  labels:
   {{- include "webhook.labels" . | nindent 4 }}
  namespace: {{ .Values.webhook.namespace }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
      name: {{ .Values.webhook.service.name }}
  selector:
    {{- include "webhook.selectorLabels" . | nindent 6 }}
{{- end }}