{{- if .Values.sidecar.enabled }}
{{- if (index .Values "ingress-nginx" "install") -}}{{ fail "ingress-nginx cannot be enabled in sidecar mode"}}{{- end -}}
{{ $tls := fromYaml ( include "webhook.gen-certs" . ) }}
{{- if .Values.sidecar.webhook.cert.create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
   {{- include "webhook.labels" . | nindent 4 }}
  name: {{ .Values.sidecar.webhook.cert.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  # Cert for {{ include "webhook.service.fullname" . }}
  tls.crt: {{ $tls.clientCert }}
  tls.key: {{ $tls.clientKey }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.sidecar.webhook.name }}
  labels:
   {{- include "webhook.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      # url: "https://codesealer-mutating-webhook.codesealer-system.svc.cluster.local/mutate-codesealer"
      caBundle: {{ $tls.caCert }}
      service:
        name: {{ .Values.sidecar.webhook.name }}
        namespace: {{ .Values.namespace }}
        path: {{ .Values.sidecar.webhook.path }}
        port: {{ .Values.sidecar.webhook.service.port }}
    failurePolicy: {{ .Values.sidecar.webhook.failurePolicy }}
    matchPolicy: Equivalent
    name: mutating-webhook.codesealer.com
    namespaceSelector:
      matchExpressions:
        - key: codesealer.com/webhook
          operator: In
          values:
            - enabled
    objectSelector: {}
    reinvocationPolicy: {{ .Values.sidecar.webhook.reinvocationPolicy }}
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "v1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - "pods"
        scope: "Namespaced"
    sideEffects: {{ .Values.sidecar.webhook.sideEffects }}
    timeoutSeconds: {{ .Values.sidecar.webhook.timeout }}
{{- end }}
