apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.redis.name }}
  labels:
   {{- include "redis.labels" . | nindent 4 }}
  namespace: {{ .Values.redis.namespace }}
data:
  redis.conf: |+
    cluster-enabled no
    appendonly yes
    protected-mode no
    bind 0.0.0.0
    port 6379
---

